from rest_framework.status import (
    HTTP_200_OK,
    HTTP_201_CREATED,
    HTTP_202_ACCEPTED,
    HTTP_400_BAD_REQUEST,
    HTTP_401_UNAUTHORIZED,
    HTTP_403_FORBIDDEN,
    HTTP_404_NOT_FOUND,
    HTTP_409_CONFLICT,
    HTTP_429_TOO_MANY_REQUESTS,
    HTTP_500_INTERNAL_SERVER_ERROR,
    HTTP_502_BAD_GATEWAY,
    HTTP_503_SERVICE_UNAVAILABLE,
)


class STATUS:
    OK = HTTP_200_OK
    CREATED = HTTP_201_CREATED
    ACCEPTED = HTTP_202_ACCEPTED
    BAD_REQ = HTTP_400_BAD_REQUEST
    NO_AUTH = HTTP_401_UNAUTHORIZED
    PERM_ERROR = HTTP_403_FORBIDDEN
    NOT_FOUND = HTTP_404_NOT_FOUND
    CONFLICT = HTTP_409_CONFLICT
    RATE_LIMIT = HTTP_429_TOO_MANY_REQUESTS
    SERVER_ERROR = HTTP_500_INTERNAL_SERVER_ERROR
    GATEWAY_FAIL = HTTP_502_BAD_GATEWAY
    UNAVAILABLE = HTTP_503_SERVICE_UNAVAILABLE
